version: "3.7"

services:
  ping:
    build:
      context: ../ping
      dockerfile: ./Dockerfile
    image: dilwit/spring-boot-docker/ping
    ports:
      - 8085:8080
    volumes:
      - /Users/dilusha.withanage/app/spring-boot-docker/ping/config:/app/config
      - /Users/dilusha.withanage/app/spring-boot-docker/ping/log:/app/log
    environment:
      - "SPRING_PROFILES_ACTIVE=dilwit"
      - SERVICE_PONG_URL=http://pong:8080/pong

  pong:
    build:
      context: ../pong
      dockerfile: ./Dockerfile
    image: dilwit/spring-boot-docker/pong
    ports:
      - 8086:8080
    volumes:
        - /Users/dilusha.withanage/app/spring-boot-docker/pong/config:/app/config
        - /Users/dilusha.withanage/app/spring-boot-docker/pong/log:/app/log
    environment:
      - "SPRING_PROFILES_ACTIVE=dilwit"
    depends_on:
      - ping