version: '2.2'
services:
  ping:
    build:
      context: ../ping-x
      dockerfile: Dockerfile
      #dockerfile: Dockerfile-build
    image: dilwit/spring-boot-docker/ping
    ports:
      - 8080
    networks:
      - network1
    scale: 1

networks:
  network1: