version: '2.2'
services:
  pong:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: dilwit/spring-boot-docker/pong
    ports:
      - 8080
    networks:
      - network1
    scale: 1

networks:
  network1: